FROM mambaorg/micromamba:latest

ENV MAMBA_DOCKERFILE_ACTIVATE=1

RUN micromamba create -y -n spectralmatch -c conda-forge \
    python=3.13 \
    gdal>=3.11 \
    proj>=9.3 \
    numpy \
    scipy \
    pip

SHELL ["micromamba", "run", "-n", "spectralmatch", "/bin/bash", "-c"]

RUN pip install spectralmatch

CMD ["python"]