# -*- coding: utf-8 -*-

"""
/***************************************************************************
 spectralmatch
                                 A QGIS plugin
 Performant Relative Radiometric Normalization toolkit with Pseudo-Invariant Features, seamlines, and other utilities for mosaics and time series
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-15
        copyright            : (C) 2025 by Kanoa Lindiwe LLC
        email                : cankanoa@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "Kanoa Lindiwe LLC"
__date__ = "2025-06-15"
__copyright__ = "(C) 2025 by Kanoa Lindiwe LLC"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import os
import sys
import inspect

from qgis.core import QgsApplication

from .spectralmatch_qgis_provider import spectralmatchProvider
from .utils import get_python_dependency_folder

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class spectralmatchPlugin(object):
    def __init__(self):
        self.provider = None

        self.python_dependencies = get_python_dependency_folder()
        if self.python_dependencies not in sys.path:
            sys.path.insert(0, self.python_dependencies)

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = spectralmatchProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
